#! /bin/bash

echo "start_dir: $(pwd)"
start_dir=$(pwd)

echo "base_dir: $(dirname "$0")"
base_dir=$(dirname "$0")
if [ "$base_dir" != "." ]; then
  echo "Changing directory to: $base_dir"
  cd "$base_dir" || err_exit $?
  echo "pwd: $(pwd)"
fi

echo "Venv activating:"
source ../venv/bin/activate || err_exit $?
echo "Venv activated successful"

# Start app // entrypoint
cd ./src
printf "\n\033[93m%s\033[0m\n" "< Start app"
python ./app.py # &
cd ..
printf "\n\033[93m%s\033[0m\n" "< Close app"

echo "Changing directory to: $start_dir"
cd "$start_dir" || err_exit $?
echo "pwd: $(pwd)"

deactivate